<dec f='qv2ray/test/catch.hpp' l='5195' type='3'/>
<use f='qv2ray/test/catch.hpp' l='14740' c='_ZN5Catch14TestSpecParser9visitCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14764' u='r' c='_ZN5Catch14TestSpecParser15processNoneCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14780' u='r' c='_ZN5Catch14TestSpecParser15processNameCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14798' c='_ZN5Catch14TestSpecParser7endModeEv'/>
<use f='qv2ray/test/catch.hpp' l='14825' c='_ZNK5Catch14TestSpecParser13isControlCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14846' u='r' c='_ZN5Catch14TestSpecParser8separateEv'/>
