<dec f='qv2ray/test/catch.hpp' l='5189' type='3'/>
<use f='qv2ray/test/catch.hpp' l='14560' c='_ZN5Catch14TestSpecParser9visitCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14584' u='r' c='_ZN5Catch14TestSpecParser15processNoneCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14600' u='r' c='_ZN5Catch14TestSpecParser15processNameCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14618' c='_ZN5Catch14TestSpecParser7endModeEv'/>
<use f='qv2ray/test/catch.hpp' l='14645' c='_ZNK5Catch14TestSpecParser13isControlCharEc'/>
<use f='qv2ray/test/catch.hpp' l='14666' u='r' c='_ZN5Catch14TestSpecParser8separateEv'/>
