<dec f='qv2ray/src/base/models/QvSettingsObject.hpp' l='17' type='QJS_Prop&lt;int&gt;'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='25' u='w' c='_ZN6Qv2ray4base6config16QvGraphPenConfigC1EiiifN2Qt8PenStyleE'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='w' c='_ZN6Qv2ray4base6config16QvGraphPenConfigaSERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='r' c='_ZN6Qv2ray4base6config16QvGraphPenConfigaSERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='m' c='_ZNK6Qv2ray4base6config16QvGraphPenConfig6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='r' c='_ZNK6Qv2ray4base6config16QvGraphPenConfig6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='a' c='_ZN6Qv2ray4base6config16QvGraphPenConfig8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='r' c='_ZNK6Qv2ray4base6config16QvGraphPenConfigeqERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='29' u='m' c='_ZNK6Qv2ray4base6config16QvGraphPenConfigeqERKS2_'/>
<offset>1152</offset>
<use f='/qv2ray_baselib_autogen/KBQUCU6ZTO/moc_QvSettingsObject.cpp' l='151' u='m' c='_ZN6Qv2ray4base6config16QvGraphPenConfig18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv'/>
<use f='/qv2ray_baselib_autogen/KBQUCU6ZTO/moc_QvSettingsObject.cpp' l='174' u='r' c='_ZN6Qv2ray4base6config16QvGraphPenConfig18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv'/>
<use f='/qv2ray_baselib_autogen/KBQUCU6ZTO/moc_QvSettingsObject.cpp' l='175' u='w' c='_ZN6Qv2ray4base6config16QvGraphPenConfig18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv'/>
<use f='qv2ray/src/ui/common/speedchart/speedwidget.cpp' l='177' u='m' c='_ZN11SpeedWidget23UpdateSpeedPlotSettingsEv'/>
