<dec f='qv2ray/src/base/models/QvSettingsObject.hpp' l='52' type='QJS_Prop&lt;QString&gt;'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='w' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UIaSERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='r' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UIaSERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='m' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UI6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UI6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='a' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UIeqERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='m' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UIeqERKS2_'/>
<offset>128</offset>
<use f='/qv2ray_baselib_autogen/KBQUCU6ZTO/moc_QvSettingsObject.cpp' l='712' u='m' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv'/>
<use f='/qv2ray_baselib_autogen/KBQUCU6ZTO/moc_QvSettingsObject.cpp' l='731' u='r' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv'/>
<use f='/qv2ray_baselib_autogen/KBQUCU6ZTO/moc_QvSettingsObject.cpp' l='732' u='w' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI18qt_static_metacallEP7QObjectN11QMetaObject4CallEiPPv'/>
<use f='qv2ray/src/ui/widgets/Qv2rayWidgetApplication.cpp' l='134' u='m' c='_ZN6Qv2ray23Qv2rayWidgetApplication17runQv2rayInternalEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='90' u='m' c='_ZN17PreferencesWindowC1EP7QWidget'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='397' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='397' u='m' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='399' u='m' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='613' u='w' c='_ZN17PreferencesWindow32on_themeCombo_currentTextChangedERK7QString'/>
