<use f='qv2ray/3rdparty/uvw/src/uvw/underlying_type.hpp' l='29' u='a' c='_ZN3uvw14UnderlyingType3getEv'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/underlying_type.hpp' l='34' u='a' c='_ZNK3uvw14UnderlyingType3getEv'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/underlying_type.hpp' l='44' u='w' c='_ZN3uvw14UnderlyingTypeC1ENS0_17ConstructorAccessESt10shared_ptrINS_4LoopEE'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/underlying_type.hpp' l='89' u='a' c='_ZNK3uvw14UnderlyingType3rawEv'/>
<dec f='qv2ray/3rdparty/uvw/src/uvw/underlying_type.hpp' l='113' type='U'/>
