<dec f='qv2ray/src/base/models/QvSettingsObject.hpp' l='51' type='QString'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UIeqERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='64' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UIeqERKS2_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='66' u='a' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='66' u='w' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='66' u='r' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='66' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UI6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='66' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UI6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='66' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UI6toJsonEv'/>
<offset>0</offset>
<use f='qv2ray/src/ui/widgets/Qv2rayWidgetApplication.cpp' l='133' u='r' c='_ZN6Qv2ray23Qv2rayWidgetApplication17runQv2rayInternalEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='90' u='r' c='_ZN17PreferencesWindowC1EP7QWidget'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='400' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='400' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='402' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/widgets/windows/w_PreferencesWindow.cpp' l='614' u='w' c='_ZN17PreferencesWindow32on_themeCombo_currentTextChangedERK7QString'/>
