<dec f='qv2ray/src/base/models/QvSettingsObject.hpp' l='14' type='int'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='21' u='w' c='_ZN6Qv2ray4base6config16QvGraphPenConfigC1EiiifN2Qt8PenStyleE'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='28' u='r' c='_ZN6Qv2ray4base6configeqERKNS1_16QvGraphPenConfigES4_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='28' u='r' c='_ZN6Qv2ray4base6configeqERKNS1_16QvGraphPenConfigES4_'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='30' u='a' c='_ZN6Qv2ray4base6config16QvGraphPenConfig8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='30' u='w' c='_ZN6Qv2ray4base6config16QvGraphPenConfig8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='30' u='r' c='_ZN6Qv2ray4base6config16QvGraphPenConfig8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='30' u='r' c='_ZNK6Qv2ray4base6config16QvGraphPenConfig6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='30' u='r' c='_ZNK6Qv2ray4base6config16QvGraphPenConfig6toJsonEv'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='30' u='r' c='_ZNK6Qv2ray4base6config16QvGraphPenConfig6toJsonEv'/>
<offset>32</offset>
<use f='qv2ray/src/ui/common/speedchart/speedwidget.cpp' l='176' u='r' c='_ZN11SpeedWidget23UpdateSpeedPlotSettingsEv'/>
