<def f='qv2ray/3rdparty/uvw/src/uvw/util.h' l='462' ll='587'/>
<size>1</size>
<doc f='qv2ray/3rdparty/uvw/src/uvw/util.h' l='459'>/**
     * @brief OS dedicated utilities.
     */</doc>
<fun r='_ZN3uvw9Utilities2OS3pidEv'/>
<fun r='_ZN3uvw9Utilities2OS6parentEv'/>
<fun r='_ZN3uvw9Utilities2OS7homedirB5cxx11Ev'/>
<fun r='_ZN3uvw9Utilities2OS6tmpdirB5cxx11Ev'/>
<fun r='_ZN3uvw9Utilities2OS3envERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'/>
<fun r='_ZN3uvw9Utilities2OS3envERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_'/>
<fun r='_ZN3uvw9Utilities2OS3envET_'/>
<fun r='_ZN3uvw9Utilities2OS8hostnameB5cxx11Ev'/>
<fun r='_ZN3uvw9Utilities2OS5unameEv'/>
<fun r='_ZN3uvw9Utilities2OS6passwdEv'/>
