<dec f='qv2ray/src/base/models/QvSettingsObject.hpp' l='40' type='QString'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='51' u='w' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UIC1Ev'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='59' u='a' c='_ZN6Qv2ray4base6config15Qv2rayConfig_UI8loadJsonERK10QJsonValue'/>
<use f='qv2ray/src/base/models/QvSettingsObject.hpp' l='59' u='r' c='_ZNK6Qv2ray4base6config15Qv2rayConfig_UI6toJsonEv'/>
<offset>0</offset>
<use f='qv2ray/src/Qv2rayApplication.cpp' l='449' u='r' c='_ZN6Qv2ray17Qv2rayApplication25InitializeGlobalVariablesEv'/>
<use f='qv2ray/src/ui/windows/w_PreferencesWindow.cpp' l='83' u='r' c='_ZN17PreferencesWindowC1EP7QWidget'/>
<use f='qv2ray/src/ui/windows/w_PreferencesWindow.cpp' l='355' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/windows/w_PreferencesWindow.cpp' l='355' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/windows/w_PreferencesWindow.cpp' l='357' u='r' c='_ZN17PreferencesWindow21on_buttonBox_acceptedEv'/>
<use f='qv2ray/src/ui/windows/w_PreferencesWindow.cpp' l='683' u='w' c='_ZN17PreferencesWindow32on_themeCombo_currentTextChangedERK7QString'/>
