<def f='qv2ray/3rdparty/uvw/src/uvw/resource.hpp' l='20' ll='67'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/handle.hpp' l='30'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/handle.hpp' l='67'/>
<fun r='_ZNK3uvw8Resource6parentEv'/>
<fun r='_ZN3uvw8Resource4leakEv'/>
<fun r='_ZN3uvw8Resource5resetEv'/>
<fun r='_ZNK3uvw8Resource4selfEv'/>
<fun r='_ZN3uvw8ResourceC1ENS_14UnderlyingTypeIT_T0_E17ConstructorAccessESt10shared_ptrINS_4LoopEE'/>
<fun r='_ZNK3uvw8Resource4dataEv'/>
<fun r='_ZN3uvw8Resource4dataESt10shared_ptrIvE'/>
<mbr r='uvw::Resource::userData' t='std::shared_ptr&lt;void&gt;'/>
<mbr r='uvw::Resource::sPtr' t='std::shared_ptr&lt;void&gt;'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/request.hpp' l='21'/>
<use f='qv2ray/3rdparty/uvw/src/uvw/request.hpp' l='49'/>
