<dec f='qv2ray/3rdparty/zxing-cpp/core/src/Point.h' l='26' type='T'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/Point.h' l='29' u='w' c='_ZN5ZXing6PointTC1ET_S1_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/Point.h' l='32' u='w' c='_ZN5ZXing6PointTC1ERKNS_6PointTITL0__EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/Point.h' l='102' u='r' c='_ZN5ZXing5roundENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/GridSampler.cpp' l='28' u='r' c='_ZN5ZXing10SampleGridERKNS_9BitMatrixEiiRKNS_20PerspectiveTransformE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/GridSampler.cpp' l='28' u='r' c='_ZN5ZXing10SampleGridERKNS_9BitMatrixEiiRKNS_20PerspectiveTransformE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/GridSampler.cpp' l='39' u='r' c='_ZN5ZXing10SampleGridERKNS_9BitMatrixEiiRKNS_20PerspectiveTransformE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/ResultPoint.h' l='38' u='r' c='_ZNK5ZXing11ResultPoint1yEv'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/PerspectiveTransform.cpp' l='92' u='r' c='_ZNK5ZXing20PerspectiveTransformclENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/PerspectiveTransform.cpp' l='93' u='r' c='_ZNK5ZXing20PerspectiveTransformclENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/PerspectiveTransform.cpp' l='93' u='r' c='_ZNK5ZXing20PerspectiveTransformclENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='222' u='r' c='_ZN5ZXing5AztecL8GetColorERKNS_9BitMatrixERKNS_6PointTIiEES7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='223' u='r' c='_ZN5ZXing5AztecL8GetColorERKNS_9BitMatrixERKNS_6PointTIiEES7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='228' u='r' c='_ZN5ZXing5AztecL8GetColorERKNS_9BitMatrixERKNS_6PointTIiEES7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='228' u='r' c='_ZN5ZXing5AztecL8GetColorERKNS_9BitMatrixERKNS_6PointTIiEES7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='232' u='r' c='_ZN5ZXing5AztecL8GetColorERKNS_9BitMatrixERKNS_6PointTIiEES7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='234' u='r' c='_ZN5ZXing5AztecL8GetColorERKNS_9BitMatrixERKNS_6PointTIiEES7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='261' u='r' c='_ZN5ZXing5AztecL23IsWhiteOrBlackRectangleERKNS_9BitMatrixERKNS_6PointTIiEES7_S7_S7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='262' u='r' c='_ZN5ZXing5AztecL23IsWhiteOrBlackRectangleERKNS_9BitMatrixERKNS_6PointTIiEES7_S7_S7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='263' u='r' c='_ZN5ZXing5AztecL23IsWhiteOrBlackRectangleERKNS_9BitMatrixERKNS_6PointTIiEES7_S7_S7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='264' u='r' c='_ZN5ZXing5AztecL23IsWhiteOrBlackRectangleERKNS_9BitMatrixERKNS_6PointTIiEES7_S7_S7_'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='295' u='r' c='_ZN5ZXing5AztecL17GetFirstDifferentERKNS_9BitMatrixERKNS_6PointTIiEEbii'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='396' u='r' c='_ZN5ZXing5AztecL18GetBullsEyeCornersERKNS_9BitMatrixERKNS_6PointTIiEERSt5arrayINS_11ResultPointELm4EERbRi'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='397' u='r' c='_ZN5ZXing5AztecL18GetBullsEyeCornersERKNS_9BitMatrixERKNS_6PointTIiEERSt5arrayINS_11ResultPointELm4EERbRi'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='398' u='r' c='_ZN5ZXing5AztecL18GetBullsEyeCornersERKNS_9BitMatrixERKNS_6PointTIiEERSt5arrayINS_11ResultPointELm4EERbRi'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/aztec/AZDetector.cpp' l='399' u='r' c='_ZN5ZXing5AztecL18GetBullsEyeCornersERKNS_9BitMatrixERKNS_6PointTIiEERSt5arrayINS_11ResultPointELm4EERbRi'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='437' u='r' c='_ZN5ZXing10DataMatrix14RegressionLine8evaluateERKSt6vectorINS_6PointTIiEESaIS4_EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='437' u='r' c='_ZN5ZXing10DataMatrix14RegressionLine8evaluateERKSt6vectorINS_6PointTIiEESaIS4_EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='437' u='r' c='_ZN5ZXing10DataMatrix14RegressionLine8evaluateERKSt6vectorINS_6PointTIiEESaIS4_EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='437' u='r' c='_ZN5ZXing10DataMatrix14RegressionLine8evaluateERKSt6vectorINS_6PointTIiEESaIS4_EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='438' u='r' c='_ZN5ZXing10DataMatrix14RegressionLine8evaluateERKSt6vectorINS_6PointTIiEESaIS4_EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='438' u='r' c='_ZN5ZXing10DataMatrix14RegressionLine8evaluateERKSt6vectorINS_6PointTIiEESaIS4_EE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='569' u='r' c='_ZN5ZXing10DataMatrix10EdgeTracer13mainDirectionENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='570' u='r' c='_ZN5ZXing10DataMatrix10EdgeTracer13mainDirectionENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='570' u='r' c='_ZN5ZXing10DataMatrix10EdgeTracer13mainDirectionENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='579' u='r' c='_ZNK5ZXing10DataMatrix10EdgeTracer4isInENS_6PointTIiEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='579' u='r' c='_ZNK5ZXing10DataMatrix10EdgeTracer4isInENS_6PointTIiEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='601' u='r' c='_ZNK5ZXing10DataMatrix10EdgeTracer5getAtENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='672' u='r' c='_ZN5ZXing10DataMatrix10EdgeTracer12setDirectionENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='682' u='r' c='_ZN5ZXing10DataMatrix10EdgeTracer25updateDirectionFromOriginENS_6PointTIdEE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='690' u='r' c='_ZNK5ZXing10DataMatrix10EdgeTracer4backEv'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='691' u='r' c='_ZNK5ZXing10DataMatrix10EdgeTracer5rightEv'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/datamatrix/DMDetector.cpp' l='692' u='r' c='_ZNK5ZXing10DataMatrix10EdgeTracer4leftEv'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/oned/ODReader.cpp' l='188' u='r' c='_ZN5ZXing4OneDL8DoDecodeERKSt6vectorISt10unique_ptrINS0_9RowReaderESt14default_deleteIS3_EESaIS6_EERKNS_12BinaryBitmapEb'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/oned/ODReader.cpp' l='219' u='r' c='_ZNK5ZXing4OneD6Reader6decodeERKNS_12BinaryBitmapE'/>
<use f='qv2ray/3rdparty/zxing-cpp/core/src/qrcode/QRFinderPatternFinder.cpp' l='319' u='r' c='_ZN5ZXing6QRCodeL11FindRowSkipERKSt6vectorINS0_13FinderPatternESaIS2_EERb'/>
