name: Build Source Viewer

on:
  push:
    branches: [ source ]
  schedule:
    - cron: 0 0,12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debugging with tmate
        # You may pin to the exact commit or the version.
        # uses: mxschmitt/action-tmate@03e13f10cd0b4e4d7002dbb0f55e7dd92b7fb9d6
        uses: mxschmitt/action-tmate@v3.4
      - run: |
          sudo apt update
          sudo apt install -y libcurl4-openssl-dev llvm llvm-dev clang libclang-dev ninja-build
          git submodule update --init
          cd woboq_codebrowser
          mkdir build; cd build;
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --parallel $(nproc)

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-5.15

      - name: Installing Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.1
          mirror: "http://mirrors.ocf.berkeley.edu/qt/"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - run: |
          sudo apt install -y libgl-dev libx11-dev libxkbcommon-x11-dev libxcb-image0-dev libxcb-icccm4-dev libssl-dev libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0
          sudo apt install -y libprotobuf-dev protobuf-compiler protobuf-c-compiler libgrpc++-dev protobuf-compiler-grpc

      - run: |
          QV2RAY_BUILD_BRANCH=dev ./export.sh
          QV2RAY_BUILD_BRANCH=version-v2 ./export.sh
          QV2RAY_BUILD_BRANCH=master ./export.sh

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: master
          keep_history: false
          build_dir: ./doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
