# This is a basic workflow to help you get started with Actions

name: Build Source Viewer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the source branch
on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          sudo dd if=/dev/zero of=/swapfile bs=1024 count=4000000 status=progress
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: QtCache-5.15
      - name: Installing Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.1
          mirror: "http://mirrors.ocf.berkeley.edu/qt/"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - run: |
          sudo apt update
          sudo apt install -y libgl-dev libx11-dev libxkbcommon-x11-dev libxcb-image0-dev libxcb-icccm4-dev libssl-dev libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0
          sudo apt install -y libprotobuf-dev protobuf-compiler protobuf-c-compiler libgrpc++-dev protobuf-compiler-grpc ninja-build
          sudo apt install -y libcurl4-openssl-dev llvm-9 clang-9 libclang-9-dev
          export QV2RAY_BUILD_BRANCH=dev
          ./export.sh || true
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: master
          keep_history: false
          build_dir: ./doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
